wandb_version: 1

D:
  desc: null
  value: 784
M:
  desc: null
  value: 8000
lr:
  desc: null
  value: 0.001
n_masks:
  desc: null
  value: 1
num_epochs:
  desc: null
  value: 1
max_patience:
  desc: null
  value: 5
batch_size:
  desc: null
  value: 64
lambda:
  desc: null
  value: 0.0
_wandb:
  desc: null
  value:
    python_version: 3.11.4
    cli_version: 0.17.0
    framework: torch
    is_jupyter_run: true
    is_kaggle_kernel: false
    start_time: 1719091239
    t:
      1:
      - 1
      - 5
      - 41
      - 53
      - 55
      2:
      - 1
      - 5
      - 41
      - 53
      - 55
      3:
      - 2
      - 13
      - 14
      - 16
      - 23
      - 37
      4: 3.11.4
      5: 0.17.0
      8:
      - 1
      - 4
      - 6
      13: darwin-arm64
