wandb_version: 1

_wandb:
  desc: null
  value:
    python_version: 3.11.4
    cli_version: 0.17.0
    framework: torch
    is_jupyter_run: true
    is_kaggle_kernel: false
    start_time: 1719760646
    t:
      1:
      - 1
      - 5
      - 41
      - 53
      - 55
      2:
      - 1
      - 5
      - 41
      - 53
      - 55
      3:
      - 2
      - 23
      - 37
      4: 3.11.4
      5: 0.17.0
      8:
      - 1
      - 4
      - 5
      13: darwin-arm64
batch_size:
  desc: null
  value: 64
input_dim:
  desc: null
  value: 784
lam:
  desc: null
  value: 0.5
lr:
  desc: null
  value: 0.01
max_patience:
  desc: null
  value: 30
num_epochs:
  desc: null
  value: 1
num_input_units:
  desc: null
  value: 8
num_sum_units:
  desc: null
  value: 8
