wandb_version: 1

_wandb:
  desc: null
  value:
    python_version: 3.11.4
    cli_version: 0.17.0
    framework: torch
    is_jupyter_run: true
    is_kaggle_kernel: false
    start_time: 1719327351
    t:
      1:
      - 1
      - 5
      - 41
      - 53
      - 55
      3:
      - 23
      4: 3.11.4
      5: 0.17.0
      8:
      - 1
      - 5
      13: darwin-arm64
