wandb_version: 1

batch_size:
  value: 256
input_dim:
  value: 784
lam:
  value: 0.5
lr:
  value: 0.01
max_patience:
  value: 30
num_epochs:
  value: 1
num_input_units:
  value: 8
num_sum_units:
  value: 8
