wandb_version: 1

_wandb:
  desc: null
  value:
    python_version: 3.11.4
    cli_version: 0.17.0
    is_jupyter_run: true
    is_kaggle_kernel: false
    start_time: 1717069004
    t:
      1:
      - 55
      2:
      - 1
      - 5
      - 41
      - 53
      - 55
      3:
      - 19
      - 23
      4: 3.11.4
      5: 0.17.0
      8:
      - 1
      - 4
      - 5
      13: darwin-arm64
    framework: torch
learning_rate:
  desc: null
  value: 0.001
input_dim:
  desc: null
  value: 784
hidden_dim:
  desc: null
  value: 784
num_epochs:
  desc: null
  value: 1000
num_flows:
  desc: null
  value: 8
max_patience:
  desc: null
  value: 20
